---
- name: subscription-manager clean
  command: subscription-manager clean

#- name: yum clean all
#  command: yum clean all

- name: "enable product-id.conf"
  lineinfile:
    path: /etc/yum/pluginconf.d/product-id.conf
    regexp: '^enabled*'
    line: 'enabled=0'

- name: "enable "
  lineinfile:
    path: /etc/yum/pluginconf.d/product-id.conf
    regexp: '^enabled*'
    line: 'enabled=0'

- name: remove katello-ca-consumer-jarvis packages
  yum:
    name: katello-ca-consumer-bulgaria*
    state: absent

- name: Download katello-ca-consumer-latest
  shell: 'curl https://pandora.sdab.sn/pub/katello-ca-consumer-latest.noarch.rpm -o katello-ca-consumer-latest.noarch.rpm -ks' 

- name: Update katello-ca-consumer
  shell: "rpm -Uvh ./katello-ca-consumer-latest.noarch.rpm "
#- name: register in jarvis RHEL6
#  shell: 'subscription-manager register --org="lifecell" --activationkey="rhel6-prod" --force'
#  ignore_errors: true
#  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6'

- name: register in jarvis RHEL7
  shell: 'subscription-manager register --org="lifecell" --activationkey="rhel7-prod" --force'
  ignore_errors: true
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: register in jarvis RHEL8
  shell: 'subscription-manager register --org="lifecell" --activationkey="rhel8-prod" --force'
  ignore_errors: true
  when:  ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'

- name:  register in jarvis OEL7
  shell: 'subscription-manager register --org="lifecell" --activationkey="oel7-prod" --force'
  ignore_errors: true
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '7'

- name: register in jarvis OEL8
  shell: 'subscription-manager register --org="lifecell" --activationkey="oel8-prod" --force'
  ignore_errors: true
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == '8'

- name: "rm -f /etc/pki/product-default/69.pem"
  shell: rm -f /etc/pki/product-default/69.pem

- name: "rm -f /etc/pki/product/*"
  shell: rm -f /etc/pki/product/*


