# tasks file for OSupdate
---
- import_tasks: preupdateOS_prod.yaml
  tags:
    - never
    - update
    - preupdate_check

- import_tasks: preupdateOS_test.yaml
  tags:
    - never
    - update
    - preupdate_check

- import_tasks: virt_or_hard_host.yaml
  tags:
    - never
    - update
    - preupdate_check

- import_tasks: updateOS.yaml
  tags:
    - never
    - update
    
- import_tasks: reboot.yaml
  tags:
    - never
    - reboot

- import_tasks: check_OS_version.yaml
  tags:
    - never
    - update
    - check_OS_version

- import_tasks: check_kernel_version.yaml
  tags:
    - never
    - update
    - check_kernel_version